name: Unit Tests
# Runs unit tests against main branch only

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            VERSION

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pytest (runner only)
        run: pip install pytest

      - name: Install package (no extras) for compile-only check
        # Proves base install/import works without optional deps
        run: pip install .

      - name: Compile-only check
        run: pytest ./tests/test_compile.py

      - name: Install package with dev extras
        run: pip install .[dev]

      - name: Lint with flake8
        run: flake8 geostructures --count --show-source --statistics --max-line-length=120

      - name: Run tests with coverage
        run: |
          coverage run --source geostructures -m pytest --ignore ./tests/test_compile.py
          coverage report -m --fail-under 99

      - name: Type check (mypy)
        run: mypy geostructures
